name: multis-ws
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - abinit=10.0.3
  - ase=3.28.0
  - numpy=2.5.0
  - matplotlib=3.10.9
  - scipy=1.17.1
  - tqdm=4.66.0
  - jupyterlab=4.5.8
  - ipykernel